language: node_js
node_js:
- "0.12"
cache:
    directories:
    - node_modules
sudo: false
addons:
    postgresql: "9.4"
    apt:
        packages:
        - libcairo2-dev
        - libjpeg8-dev
        - libpango1.0-dev
        - libgif-dev
        - build-essential
        - g++
before_script:
- psql -c 'create database continua11y_test;' -U postgres
- psql -c 'create database continua11y;' -U postgres
script: npm test --coverage
after_script:
- codeclimate-test-reporter < coverage/lcov.info
- npm install -g pa11y-crawl
- pa11y-crawl --run "npm start" --ci http://localhost:3000
notifications:
    email: false
env:
    global:
    - GITHUB_TOKEN=FAKE_TEST_TOKEN
    - CF_USERNAME=18f-acq_deployer
    - secure: "lgJhmljgx5JWK8/WZNkyF5tkSg9AMWhjiglHp/TQaCymVDED68ZsiHD1PxXpY2364uluTYxhb5yBsjwNV1Ss0V7MGd5WIOxY6kDCC6Kt+p3iEs7uBxkUWcsutW76n1sRziAEKIW0KOseikPN4WO1RGuuR2XPRNIb9pNXDhqeQ/s="
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0"
- tar xzvf $HOME/cf.tgz -C $HOME
- mkdir -p ${HOME}/Godeps/_workspace
- export GOPATH=${HOME}/Godeps/_workspace
- go get github.com/concourse/autopilot
- cf install-plugin -f $GOPATH/bin/autopilot
deploy:
  app: cob-continua11y
  provider: heroku
  on: release
  api_key:
    secure: V772eQDr0huLITcpvxCsWuzMxyNHccdRou+utfoP4z7ei4lt+Oq7R2bETLO+fcrmLNOV29a4IiF0p2uAH91bWn74wd2aaNoSu2ueMei4gtxwXF/Qiaf4IkKn+yUqxl39ZTekim/AAHY2eE4MtdjDmxfVB3ddcYmMFbv5oW/e0XFW8yjmjz1b1GelA5dvghh5htP3xPbdNPz6+VaNXLQp0loc8f7VAcE5IEm+9UJsiw5iltFmIG7qWEvJeqB9msAl3/KpUC1rjyDvYPcHfF+GwibtEZXdWr66mD44QsuFNL+ho073dIDJdv7qBUI7JzUyNCOckJ+H00tUyujwg1WMa92S6JLtHQLLYNq4Dr1IOOPNRVkvzvM/sK2aXepAnp6QbMMsEe48gT/OkkFbWBcqSAqmZrd2YpTBPjxqnKDguwdL+tot+qFY8l9IyKztLnL4QK56xFUXuzZtZrCRNxk0YzVK8IJwjsnePtEsZSoY8pJ+ZriBuTfiFywyfJTFWWroqUUcHVvE+FqUPGajk53Ys19bvlB3CEzYSYeTskboS898BhXlpCu/FRHI+qjXuvOpwO99tZ5RH3s62Gh+FIUecJMHWmQASUAZlqrypmyiLG6d7lNI+6AEGrIH9G6dEWjA7C75ZMuEj1NjVStn7vuiDmuU0QmmOK+M9ckTG16jJ8Q=
