language: node_js
node_js:
- '0.12'
cache:
  directories:
  - node_modules
sudo: false
addons:
  postgresql: '9.4'
  apt:
    packages:
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
    - g++
before_script:
- psql -c 'create database continua11y_test;' -U postgres
- psql -c 'create database continua11y;' -U postgres
script: npm test --coverage
after_script:
- npm install -g pa11y-crawl
- pa11y-crawl --run "npm start" --ci https://cob-continua11y.herokuapp.com
notifications:
  email: false
env:
  global:
  - GITHUB_TOKEN=FAKE_TEST_TOKEN
  - secure: lgJhmljgx5JWK8/WZNkyF5tkSg9AMWhjiglHp/TQaCymVDED68ZsiHD1PxXpY2364uluTYxhb5yBsjwNV1Ss0V7MGd5WIOxY6kDCC6Kt+p3iEs7uBxkUWcsutW76n1sRziAEKIW0KOseikPN4WO1RGuuR2XPRNIb9pNXDhqeQ/s=
deploy:
  app: cob-continua11y
  provider: heroku
  on: release
  api_key:
    secure: AwGhhvxns4dYyZf0GF5L4RK6KyIP3cp57Jn8Xqk6zmbkDlrVYUiOtngTpw5LFUUbCGMtAzvv4w0DalWcd4WyVzeWfvXf5vnPiE2h10ei7BwWf/UidGCqlgJdgLKuJzRsRCRtwKzXkLVHk6OJ1e8Q/iZ1n+77a86jWBC6X0IuR7qOIQuf1c0bycCDB5FzEq8ppxAJpKr+Wqp618qgqWekeFTYEgKctCsNN99kOylFFxjIjEN1bsnlnc5gIGKVVbrQskBJEMPpL+rRBLp0CqxVMp7P33lcE4lDBAlzZlp0plIKRgu23zNYXE1iBzka12Of7rtxyD1ZnxhdLdZvcHYQSAp5PHPIWZqssBWIM42JkbO0cl0V4tPZcD04eWaDnWubUdF7+NVQezFp/5RCtJebc5r5MH4MW+GCrJbrZbVowdd56bqOXSTopGCQOIQzA3j+v44iLltnd9el7HXM/rhgylWLZ7muBsqkFNNtXxKF4aLXrBZ6phrVboGFzsoNuevqgKMRci0JUuovGoc65YbJKmmAxeoHP1HaHd6Xll9Y8Q4ukMLjtlXxQoKy/EyP+qxjpMNhUEBT6LiLS2JubujzGpo7wZC4s00nzq9d8BzaiptGvl8P7HAU9O+jL0Wb+TCTeW3/PW7wtyve6YBLxXw8bXdfpyG6ERilNqtMWAOBpz8=
